/** Canonical BM status value -> i18n key under sppt.status */
export const SPPT_STATUS_I18N_KEYS: Record<string, string> = {
  Draf: "sppt.status.draf",
  "Dalam Proses": "sppt.status.dalamProses",
  "Menunggu Dokumen": "sppt.status.menungguDokumen",
  Lengkap: "sppt.status.lengkap",
  Menunggu: "sppt.status.menunggu",
  "Dalam Penilaian": "sppt.status.dalamPenilaian",
  Diluluskan: "sppt.status.diluluskan",
  Ditolak: "sppt.status.ditolak",
  Disemak: "sppt.status.disemak",
  Disokong: "sppt.status.disokong",
  Berjaya: "sppt.status.berjaya",
  Gagal: "sppt.status.gagal",
  "Menunggu Kelulusan": "sppt.status.menungguKelulusan",
  Diproses: "sppt.status.diproses",
  "Sebahagian Gagal": "sppt.status.sebahagianGagal",
  Aktif: "sppt.status.aktif",
  Selesai: "sppt.status.selesai",
  Tunggakan: "sppt.status.tunggakan",
  NPF: "sppt.status.npf",
  Dibekukan: "sppt.status.dibekukan",
  Batal: "sppt.status.batal",
  "Tamat Tempoh": "sppt.status.tamatTempoh",
  Dilepaskan: "sppt.status.dilepaskan",
  "Perlu Semakan": "sppt.status.perluSemakan",
  "Tidak Aktif": "sppt.status.tidakAktif",
  "Janji Bayar": "sppt.status.janjiBayar",
  "Dalam Tindakan Kutipan": "sppt.status.dalamTindakanKutipan",
  "Sedia untuk Tindakan Undang-Undang": "sppt.status.sediaTindakanUndangUndang",
  "Belum Selesai": "sppt.status.belumSelesai",
  "Dalam Tindakan": "sppt.status.dalamTindakan",
  Ditandatangani: "sppt.status.ditandatangani",
  Disahkan: "sppt.status.disahkan",
  Dijana: "sppt.status.dijana",
  Penyelenggaraan: "sppt.status.penyelenggaraan",
  Belum: "sppt.status.belum",
  Scheduled: "sppt.status.scheduled",
  "Menunggu Pengesahan": "sppt.status.menungguPengesahan",
  "Menunggu Pengeluaran": "sppt.status.menungguPengeluaran",
  "Write Off": "sppt.status.writeOff",
  "Meninggal Dunia": "sppt.status.meninggalDunia",
  Reschedule: "sppt.status.reschedule",
  Hadir: "sppt.status.hadir",
  "Tidak Hadir": "sppt.status.tidakHadir",
  RSVP: "sppt.status.rsvp",
  padan: "sppt.status.padan",
  manual: "sppt.status.manual",
  auto: "sppt.status.auto",
  unverified: "sppt.status.unverified",
  offset: "sppt.status.offset",
  advance: "sppt.status.advance",
  tunggakan: "sppt.status.tunggakanLower",
};

const STATUS_CLASS_MAP: Record<string, string> = {
  Draf: "bg-blue-100 text-blue-700",
  "Dalam Proses": "bg-amber-100 text-amber-700",
  "Menunggu Dokumen": "bg-slate-100 text-slate-600",
  Lengkap: "bg-emerald-100 text-emerald-700",
  Menunggu: "bg-slate-100 text-slate-600",
  "Dalam Penilaian": "bg-amber-100 text-amber-700",
  Diluluskan: "bg-emerald-100 text-emerald-700",
  Ditolak: "bg-rose-100 text-rose-700",
  Disemak: "bg-blue-100 text-blue-700",
  Disokong: "bg-indigo-100 text-indigo-700",
  Berjaya: "bg-emerald-100 text-emerald-700",
  Gagal: "bg-rose-100 text-rose-700",
  "Menunggu Kelulusan": "bg-amber-100 text-amber-700",
  Diproses: "bg-blue-100 text-blue-700",
  "Sebahagian Gagal": "bg-orange-100 text-orange-700",
  Aktif: "bg-emerald-100 text-emerald-700",
  Selesai: "bg-slate-100 text-slate-600",
  Tunggakan: "bg-amber-100 text-amber-700",
  NPF: "bg-red-100 text-red-700",
  Dibekukan: "bg-blue-100 text-blue-700",
  Batal: "bg-slate-100 text-slate-500",
  "Tamat Tempoh": "bg-amber-100 text-amber-700",
  Dilepaskan: "bg-slate-100 text-slate-600",
  "Perlu Semakan": "bg-amber-100 text-amber-800",
  "Tidak Aktif": "bg-slate-100 text-slate-500",
  "Janji Bayar": "bg-blue-100 text-blue-700",
  "Dalam Tindakan Kutipan": "bg-amber-100 text-amber-700",
  "Sedia untuk Tindakan Undang-Undang": "bg-rose-100 text-rose-700",
  "Belum Selesai": "bg-amber-100 text-amber-700",
  "Dalam Tindakan": "bg-blue-100 text-blue-700",
  Ditandatangani: "bg-blue-100 text-blue-700",
  Disahkan: "bg-emerald-100 text-emerald-700",
  Dijana: "bg-slate-100 text-slate-600",
  Penyelenggaraan: "bg-amber-100 text-amber-700",
};

export function spptStatusClass(status?: string | null): string {
  if (!status) return "bg-slate-100 text-slate-600";
  return STATUS_CLASS_MAP[status] ?? "bg-slate-100 text-slate-600";
}

export function spptStatusI18nKey(status?: string | null): string | undefined {
  if (!status) return undefined;
  return SPPT_STATUS_I18N_KEYS[status];
}
