<?php

return [
    'categories' => [
        'status_permohonan' => [
            'label' => 'Status Permohonan',
            'labelEn' => 'Application Status',
            'description' => 'Status aliran kerja permohonan pembiayaan',
        ],
        'status_penilaian' => [
            'label' => 'Status Penilaian',
            'labelEn' => 'Assessment Status',
            'description' => 'Status penilaian dan kelulusan pembiayaan',
        ],
        'status_akaun' => [
            'label' => 'Status Akaun',
            'labelEn' => 'Account Status',
            'description' => 'Status akaun pembiayaan aktif',
        ],
        'status_pengeluaran_dana' => [
            'label' => 'Status Pengeluaran Dana',
            'labelEn' => 'Fund Disbursement Status',
            'description' => 'Status pengeluaran dan batch dana',
        ],
        'status_jaminan' => [
            'label' => 'Status Jaminan',
            'labelEn' => 'Collateral Status',
            'description' => 'Status jaminan dan cagaran',
        ],
        'status_kutipan' => [
            'label' => 'Status Kutipan',
            'labelEn' => 'Collection Status',
            'description' => 'Status lawatan dan kutipan lapangan',
        ],
        'status_usahawan' => [
            'label' => 'Status Usahawan',
            'labelEn' => 'Entrepreneur Status',
            'description' => 'Status rekod usahawan',
        ],
        'status_bayaran' => [
            'label' => 'Status Bayaran',
            'labelEn' => 'Payment Status',
            'description' => 'Status transaksi bayaran pembiayaan',
        ],
        'kelayakan_tekun_niaga' => [
            'label' => 'Kelayakan TEKUN Niaga',
            'labelEn' => 'TEKUN Niaga Eligibility',
            'description' => 'Siapa yang layak untuk memohon skim pembiayaan TEKUN Niaga',
            'type' => 'knowledge',
        ],
    ],

    'defaults' => [
        'status_permohonan' => [
            ['value' => 'dalam-proses', 'label' => 'Dalam Proses', 'color' => 'amber', 'active' => true, 'sort' => 1],
            ['value' => 'menunggu-dokumen', 'label' => 'Menunggu Dokumen', 'color' => 'slate', 'active' => true, 'sort' => 2],
            ['value' => 'lengkap', 'label' => 'Lengkap', 'color' => 'emerald', 'active' => true, 'sort' => 3],
            ['value' => 'ditolak', 'label' => 'Ditolak', 'color' => 'rose', 'active' => true, 'sort' => 4],
            ['value' => 'dibatalkan', 'label' => 'Dibatalkan', 'color' => 'slate', 'active' => true, 'sort' => 5],
        ],
        'status_penilaian' => [
            ['value' => 'menunggu-penilaian', 'label' => 'Menunggu Penilaian', 'color' => 'amber', 'active' => true, 'sort' => 1],
            ['value' => 'dalam-penilaian', 'label' => 'Dalam Penilaian', 'color' => 'blue', 'active' => true, 'sort' => 2],
            ['value' => 'diluluskan', 'label' => 'Diluluskan', 'color' => 'emerald', 'active' => true, 'sort' => 3],
            ['value' => 'ditolak', 'label' => 'Ditolak', 'color' => 'rose', 'active' => true, 'sort' => 4],
        ],
        'status_akaun' => [
            ['value' => 'aktif', 'label' => 'Aktif', 'color' => 'emerald', 'active' => true, 'sort' => 1],
            ['value' => 'tunggakan', 'label' => 'Tunggakan', 'color' => 'amber', 'active' => true, 'sort' => 2],
            ['value' => 'npf', 'label' => 'NPF', 'color' => 'rose', 'active' => true, 'sort' => 3],
            ['value' => 'selesai-bayar', 'label' => 'Selesai Bayar', 'color' => 'blue', 'active' => true, 'sort' => 4],
            ['value' => 'ditutup', 'label' => 'Ditutup', 'color' => 'slate', 'active' => true, 'sort' => 5],
        ],
        'status_pengeluaran_dana' => [
            ['value' => 'draf', 'label' => 'Draf', 'color' => 'slate', 'active' => true, 'sort' => 1],
            ['value' => 'menunggu', 'label' => 'Menunggu', 'color' => 'amber', 'active' => true, 'sort' => 2],
            ['value' => 'menunggu-kelulusan', 'label' => 'Menunggu Kelulusan', 'color' => 'amber', 'active' => true, 'sort' => 3],
            ['value' => 'berjaya', 'label' => 'Berjaya', 'color' => 'emerald', 'active' => true, 'sort' => 4],
            ['value' => 'gagal', 'label' => 'Gagal', 'color' => 'rose', 'active' => true, 'sort' => 5],
        ],
        'status_jaminan' => [
            ['value' => 'aktif', 'label' => 'Aktif', 'color' => 'emerald', 'active' => true, 'sort' => 1],
            ['value' => 'tamat-tempoh', 'label' => 'Tamat Tempoh', 'color' => 'amber', 'active' => true, 'sort' => 2],
            ['value' => 'dibebaskan', 'label' => 'Dibebaskan', 'color' => 'blue', 'active' => true, 'sort' => 3],
            ['value' => 'dilucuthak', 'label' => 'Dilucuthak', 'color' => 'rose', 'active' => true, 'sort' => 4],
        ],
        'status_kutipan' => [
            ['value' => 'belum-dikunjungi', 'label' => 'Belum Dikunjungi', 'color' => 'slate', 'active' => true, 'sort' => 1],
            ['value' => 'dalam-tindakan', 'label' => 'Dalam Tindakan Kutipan', 'color' => 'amber', 'active' => true, 'sort' => 2],
            ['value' => 'janji-bayar', 'label' => 'Janji Bayar', 'color' => 'blue', 'active' => true, 'sort' => 3],
            ['value' => 'berjaya', 'label' => 'Berjaya', 'color' => 'emerald', 'active' => true, 'sort' => 4],
            ['value' => 'gagal', 'label' => 'Gagal', 'color' => 'rose', 'active' => true, 'sort' => 5],
            ['value' => 'sedia-litigasi', 'label' => 'Sedia untuk Tindakan Undang-Undang', 'color' => 'rose', 'active' => true, 'sort' => 6],
            ['value' => 'berjaya-dihubungi', 'label' => 'Berjaya Dihubungi', 'color' => 'emerald', 'active' => true, 'sort' => 7],
            ['value' => 'gagal-hubungi', 'label' => 'Gagal Hubungi', 'color' => 'amber', 'active' => true, 'sort' => 8],
            ['value' => 'rujuk-litigasi', 'label' => 'Perlu Rujuk Litigasi', 'color' => 'rose', 'active' => true, 'sort' => 9],
        ],
        'status_usahawan' => [
            ['value' => 'aktif', 'label' => 'Aktif', 'color' => 'emerald', 'active' => true, 'sort' => 1],
            ['value' => 'tidak-aktif', 'label' => 'Tidak Aktif', 'color' => 'slate', 'active' => true, 'sort' => 2],
            ['value' => 'digantung', 'label' => 'Digantung', 'color' => 'amber', 'active' => true, 'sort' => 3],
        ],
        'status_bayaran' => [
            ['value' => 'menunggu', 'label' => 'Menunggu', 'color' => 'amber', 'active' => true, 'sort' => 1],
            ['value' => 'berjaya', 'label' => 'Berjaya', 'color' => 'emerald', 'active' => true, 'sort' => 2],
            ['value' => 'gagal', 'label' => 'Gagal', 'color' => 'rose', 'active' => true, 'sort' => 3],
            ['value' => 'dibatalkan', 'label' => 'Dibatalkan', 'color' => 'slate', 'active' => true, 'sort' => 4],
            ['value' => 'dikembalikan', 'label' => 'Dikembalikan', 'color' => 'blue', 'active' => true, 'sort' => 5],
        ],
        'kelayakan_tekun_niaga' => [
            [
                'value' => '1',
                'label' => 'Bumiputera dan Warganegara Malaysia',
                'color' => 'slate',
                'active' => true,
                'sort' => 1,
            ],
            [
                'value' => '2',
                'label' => 'Berumur 18 – 65 tahun (tempoh pembiayaan tamat sehingga 65 tahun)',
                'color' => 'slate',
                'active' => true,
                'sort' => 2,
            ],
            [
                'value' => '3',
                'label' => 'Pemohon bukan seorang muflis',
                'color' => 'slate',
                'active' => true,
                'sort' => 3,
            ],
            [
                'value' => '4',
                'label' => 'Syarikat 100% hak milik Bumiputera dan warganegara',
                'color' => 'slate',
                'active' => true,
                'sort' => 4,
            ],
            [
                'value' => '5',
                'label' => 'Mempunyai Lesen / Permit / Daftar Perniagaan (SSM) / Sijil Perakuan Amalan (Program Profesional Muda) yang sah dan masih belum tamat tempoh. Untuk informal, pengesahan menjalankan perniagaan daripada Pengerusi Majlis Pembangunan Usahawan Dan Koperasi Parlimen (MPUKP) / Jawatankuasa Pembangunan dan Keselamatan Kampung (JPKK) / Jawatankuasa Pembangunan dan Keselamatan Kampung Persekutuan (JPKKP) Penghulu / Ketua Kaum (Sabah & Sarawak) atau kupon / permit perniagaan oleh Jawatankuasa Penganjur bagi perniagaan pasar malam, pasar tani atau pasar tamu',
                'color' => 'slate',
                'active' => true,
                'sort' => 5,
            ],
            [
                'value' => '6',
                'label' => 'Mempunyai tempat / lokasi perniagaan yang khusus / berniaga secara bergerak (mobile) / atas talian (online)',
                'color' => 'slate',
                'active' => true,
                'sort' => 6,
            ],
            [
                'value' => '7',
                'label' => 'Terlibat secara langsung / separuh masa dalam perniagaan',
                'color' => 'slate',
                'active' => true,
                'sort' => 7,
            ],
            [
                'value' => '8',
                'label' => 'Satu pembiayaan bagi satu isi rumah (kecuali perniagaan yang berasingan dan daftar perniagaan yang berlainan) (kecuali Program Profesional Muda)',
                'color' => 'slate',
                'active' => true,
                'sort' => 8,
            ],
            [
                'value' => '9',
                'label' => 'Had modal berbayar tidak melebihi RM300,000 (kecuali Program Profesional Muda dan Kontrak-i; RM500,000)',
                'color' => 'slate',
                'active' => true,
                'sort' => 9,
            ],
            [
                'value' => '10',
                'label' => 'Bagi pembelian kenderaan komersial / jentera berat, jumlah pembiayaan adalah 10% daripada harga kenderaan komersial / jentera berat (tertakluk kepada aliran tunai dan kedudukan kewangan pemohon)',
                'color' => 'slate',
                'active' => true,
                'sort' => 10,
            ],
            [
                'value' => '11',
                'label' => 'Bagi pemilikan Perkongsian, perlu mendapat surat kebenaran rakan kongsi yang membenarkan pemohon membuat pembiayaan',
                'color' => 'slate',
                'active' => true,
                'sort' => 11,
            ],
            [
                'value' => '12',
                'label' => 'Bagi pemilikan Syarikat Sendirian Berhad (Sdn. Bhd) wajib menyediakan Resolusi Syarikat mengikut format yang disediakan',
                'color' => 'slate',
                'active' => true,
                'sort' => 12,
            ],
            [
                'value' => '13',
                'label' => 'Aktiviti utama perniagaan usahawan mestilah patuh Syariah',
                'color' => 'slate',
                'active' => true,
                'sort' => 13,
            ],
        ],
    ],
];
